import './0-Forgot password.cy'
import './0-Register.cy'
import './1-Login-del-update bot.cy'
import './1.1-Createbot_Del.cy'
import './1.1-Profile.spec.cy'
import './1.2-Organization.cy'
import './1.2.1-Organization_Member.cy'
import './1.2.2-Org_Sub_Organization.cy'
import './1.3-Change Password.cy'
import './2-Context.cy'
import './2-Responses.cy'
import './2.1-Res-exampl.cy'
import './3-Sample.cy'
import './4-Entity types.cy'
import './5-Keywords.cy'